spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ls_prod
    username: ls_prod_user
    password: pass
    platfomr: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5DBDialect
    database: mysql
    show-sql: false