spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ls_dev
    username: ls_dev_user
    password: pass
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySql5InnoDBDialect
    database: mysql
    show-sql: true